### ISSUE TITLE
Convert existing org-links

### ISSUE THREAD

**Issue by trmd** [toshism/org-super-links#13]
I have no idea how difficult it would be, but would be great to be able to convert existing links into super-links alternatively to let regular org-links be treated as super-links (but this might perhaps be into realm of org-roam or similar solutions).

**Comment by toshism** [comment]
I hadn't thought of adding the ability to convert regular org links to super-links, but I like that idea. I'll play around with it and see what I can come up with. Thanks!

Regarding treating regular links as super-links, if you don't care about there being an actual "physical" backlink then [org-sidebar](https://github.com/alphapapa/org-sidebar) may be interesting to you.

**Comment by trmd** [comment]
Great! As I understand it, super-links still work as regular links as well?

**Comment by toshism** [comment]
They are just regular links actually. The only thing super about them is that both sides are automatically created :).

**Comment by Ypot** [comment]
Would this consist in adding the already existent backlinks into :BACKLINKS: drawers?

**Comment by toshism** [comment]
The current implementation (which i haven't included yet) only adds a backlink for an existing one way link. The backlink will be added following the users configuration. The existing link will not be altered in anyway.

**Comment by Ypot** [comment]
> The current implementation (which i haven't included yet) only adds a backlink for an existing one way link. The backlink will be added following the users configuration. The existing link will not be altered in anyway.

So, it detects links and creates the correspondent backlink for each of them.

But... what happens with the former backlinks (now obsolete) that the user had already made manually, before starting using the org-super-links package?

I suppose they will just be duplicated into the BACKLINK drawer and we will remove manually.

**Comment by Ypot** [comment]
I would like this:

1.  A link is detected

**Comment by Ypot** [comment]
I would like this:

1.  A link is detected
2.  A :DRAWER: is generated
3. The link is moved into the :DRAWER: with the chosen prefix and sufix.

Just with that it would be helpful.

If you want more:
4. The destination of the above mentioned link is analyzed
5. If in the destination there is a link, which is a BACKLINK, goto 2.
6. I there is no BACKLINK, generate one.
7. If there are links wich are not BACKLINKS, do nothing, they will be parsed later.

**Comment by toshism** [comment]
I added support for converting links finally. I struggled a bit to decide on what was the best behavior for this. After trying it out for a bit though I settled on basically respecting the current config for `sl-related-into-drawer`, but with the option of ignoring it and leaving the original link untouched.

So basically:
- with sl-related-into-drawer = something non-nil
  - add backlink
  - move existing link into drawer based on sl-related-into-drawer value

- with sl-related-into-drawer = something non-nil, but using a prefix arg (`C-u`)
  - add backlink
  - don't touch original link

- with sl-related-into-drawer = nil
  - just create the backlink
  - don't touch original link

**Comment by toshism** [comment]
@Ypot have you happened to have had a chance to try this link converting out yet? Does it work as you expected?

**Comment by Ypot** [comment]
Hi!
I have tried, but I don't know if I have my QUELPA badly configured and it doesn't update, because I can't find the command "sl-convert-link-to-super".

These are the solely candidates:
https://i.ibb.co/zbGYc7n/Captura.jpg

These are my settings (complete):
```
;; QUELPA+SUPERLINKS
(use-package quelpa
:ensure t
:config
(setq quelpa-upgrade-interval 7);; upgrade all packages once a week according to https://github.com/quelpa/quelpa
(add-hook #'after-init-hook #'quelpa-upgrade-all-maybe)
)
(use-package quelpa-use-package
:ensure t
)
(use-package org-super-links
  :quelpa (org-super-links :repo "toshism/org-super-links" :fetcher github :commit "develop")
  :bind (:map org-mode-map
	 ("C-c l" . sl-store-link)
	 :map org-mode-map
	 ("C-c C-l" . sl-insert-link)
	)
)
(setq sl-default-description-formatter 'prompt-for-desc)
(defun prompt-for-desc (link desc)
  (let ((new-desc (read-string "Description: " desc)))
    (if (string=  new-desc "")
	nil
      new-desc)))
(setq sl-backlink-prefix "- ")
(setq sl-link-prefix "- ")
(setq sl-backlink-into-drawer "LINKS"
      sl-related-into-drawer "LINKS")
(defun sl-truncate-description (link desc)
  (truncate-string-to-width desc 150))
(setq sl-default-description-formatter 'sl-truncate-description)
```

**Comment by toshism** [comment]
Have you tried running `M-x quelpa-upgrade-all`?

**Comment by Ypot** [comment]
> 
> 
> Have you tried running `M-x quelpa-upgrade-all`?

I have installed GIT.
But I have some problems:
https://github.com/toshism/org-super-links/issues/45

**Comment by Ypot** [comment]
I tried it. 
A heading "A" with an ID.
A heading "B" with a link to that ID.

In "A", a new LINK is created in a new drawer, correctly. 
But the heading "B" is erased completely xD

**Comment by toshism** [comment]
@Ypot I was doing some clean up and realized I somehow missed this! Sorry about that! 

There has been quite a bit of refactoring since this. Do you think you could try it again now?

**Comment by Ypot** [comment]
> 
> 
> @Ypot I was doing some clean up and realized I somehow missed this! Sorry about that!
> 
> There has been quite a bit of refactoring since this. Do you think you could try it again now?

It seems that when you try to convert links between 2 headings in 2 different buffers, the first heading is deleted.

**Comment by toshism** [comment]
hmm... i can't seem to recreate this. could you post your org-super-links config?

**Comment by Ypot** [comment]
Of course, this is my config:

```
(use-package quelpa
:ensure t
:config
(setq quelpa-upgrade-interval 7)
;;upgrade all packages once a week according to https://github.com/quelpa/quelpa
(add-hook #'after-init-hook #'quelpa-upgrade-all-maybe)
)
(use-package quelpa-use-package
:ensure t
)
(use-package org-super-links
  :quelpa (org-super-links :repo "toshism/org-super-links" :fetcher github :commit "develop")
  :bind (:map org-mode-map
	 ("C-c l" . sl-store-link)
	 :map org-mode-map
	 ("C-c C-l" . sl-insert-link)
	)
)
(setq sl-default-description-formatter 'prompt-for-desc)
(defun prompt-for-desc (link desc)
  (let ((new-desc (read-string "Description: " desc)))
    (if (string=  new-desc "")
	nil
      new-desc)))
(setq sl-backlink-prefix "- ")
(setq sl-link-prefix "- ")
(setq sl-backlink-into-drawer "LINKS"
      sl-related-into-drawer "LINKS")
(defun sl-truncate-description (link desc)
  (truncate-string-to-width desc 150))
(setq sl-default-description-formatter 'sl-truncate-description)
```
