### ISSUE TITLE
Can't export related drawers containing non-ID-links

### ISSUE THREAD

**Issue by novoid** [toshism/org-super-links#22]
Hi,

I just noticed that there seems to be an issue with exporting to TeX/PDF or Markdown and pretty sure for any format. It seems to be the case that only `RELATED` drawers containing fragile links (not ID-links):

```
*** A linked heading for testing
:PROPERTIES:
:CREATED:  [2020-07-09 Thu 23:07]
:END:
:RELATED:
[2020-07-09 Thu 23:08] -> [[*Heading with a backlink using fragile links][Heading with a backlink using fragile links]]
:END:
```
Results in:
`user-error: Unable to resolve link: "*Heading with a backlink using fragile links"`

The linked heading exists within the very same buffer. Somehow, the export method does not like that.

I haven't observed this behavior when using ID links.

**Comment by toshism** [comment]
That's standard org-mode export behavior (from ox.el) and not related to org-super-links. Are you exporting only that subheading? 

You may try setting `org-export-with-broken-links` to non-nil, but i'm not sure exactly what that will do in the case of the subheading export since there won't actually be anything to link to.

If you experience different behavior with a "related" or org-super-link than with a standard org link though please let me know.

**Comment by novoid** [comment]
> That's standard org-mode export behavior (from ox.el) and not related to org-super-links. Are you exporting only that subheading?

I was only exporting the sub-heading. Yes, I should have mentioned that in the first place.

> You may try setting `org-export-with-broken-links` to non-nil, but i'm not sure exactly what that will do in the case of the subheading export since there won't actually be anything to link to.

I knew that this is standard behavior. I should have expressed me more carefully. What I wanted to say - but didn't - was twofold.

First, that issue arises only with non-ID links which puzzled me. I don't understand why this is different between non-ID links and ID links. IMHO this should show the very same behavior.

Secondly, with related-links like that all over the place, there is a high chance that people run into this issue. You might want to add the non-nil setting of `org-export-with-broken-links` in the README as well.

**Off-topic:**
Sorry when I may be too demanding. I'm very grateful for your project and your time. Furthermore, I've got the feeling that your project is adding enormous value to the Org universe. Especially for people like me who do like to have some properties of Zettelkasten features such as backlinks without using the Zettelkasten method which is much more than just links.

If I would be more profound with Elisp, I'd love to contribute things like #21 myself.

**Comment by toshism** [comment]
> Secondly, with related-links like that all over the place, there is a high chance that people run into this issue. You might want to add the non-nil setting of `org-export-with-broken-links` in the README as well.

That's a good point I hadn't considered as i only use id links. I will at least mention that in the readme. Thanks!

> 
> **Off-topic:**
> Sorry when I may be too demanding. I'm very grateful for your project and your time. Furthermore, I've got the feeling that your project is adding enormous value to the Org universe. Especially for people like me who do like to have some properties of Zettelkasten features such as backlinks without using the Zettelkasten method which is much more than just links.

Thanks, that is nice to hear, and no apology necessary. I like getting feedback and suggestions.

> 
> If I would be more profound with Elisp, I'd love to contribute things like #21 myself.

I'm not ignoring that request by the way, I just want to read through the edna docs a bit to get a better idea of how it works etc.

**Comment by toshism** [comment]
finally added a note to the documentation regarding this. thanks!
