### ISSUE TITLE
Purge statistics cookies from generated link descriptions

### ISSUE THREAD

**Issue by novoid** [toshism/org-super-links#23]
_Disclaimer: This is not a bug per se, more a personal strong guess that this might cause issues in various situations which can be easily avoided._

I suggest to **remove [statistic cookies](https://orgmode.org/manual/Breaking-Down-Tasks.html#Breaking-Down-Tasks) like `[2/5]` or `[25%]` from the generated link descriptions** such as:

```
** [3/5] target heading text
:PROPERTIES:
:ID: the-id
:END:

[...]

** an example heading
:RELATED:
[2020-07-11 Sat 15:24] -> [[id:the-id][[2/5] target heading text]]
:END:
```

The **potential issue** here are the nested square brackets. Some less-tested Org packages might stumble over it according my experience.

In my opinion, this can be easily prevented by removing them from the link description. **They offer no benefit** since they don't get updated when the original heading cookies change as shown in the example above.

When `org-super-links` creates links, it strips todo keywords such as `TODO` or `WAITING` from the link description. The same rationale should be in place with removing statistics cookies as well.

Please note that the position of statistic cookies are not limited to the begin of the heading title.

**Comment by toshism** [comment]
Yeah, this makes sense. What about an config setting to prompt for a description the same way `org-insert-link` does?

**Comment by novoid** [comment]
I personally would prefer a setting where I may disable things like statistics cookies, priorities (next issue) as well as date/time-stamps in general. I dislike doing them manually when inserting.

However, this might just me because I happen to link headings with those things all the time.

And the more I'm using `org-super-links`, the more I love it. Again: thanks for this great improvement to my daily workflows!

**Comment by novoid** [comment]
See my fix using `sl-default-description-formatter` in #25.
