### ISSUE TITLE
Spread backlinks to all related headings

### ISSUE THREAD

**Issue by Ypot** [toshism/org-super-links#24]
Instead of creating just 1 link, could backlinks spread links more widely between related Heads?

For example:

```
* TODO Test heading target
  :PROPERTIES:
  :ID:       02a5da87-46e5-4ae0-85c1-ee63a570270a
  :END:
  :BACKLINKS:
  [2020-04-11 Sat 00:26] <- [[id:3835d3d0-931a-4a45-a015-a3d6a0baa99a][This has a link]]
  [2020-04-11 Sat 00:26] <- [[id:3835d3d0-931a-4a45-a015-a3d6a0baa99b][This has a link too]]
  :END:

This has 2 backlinks as you can see from the BACKLINKS drawer above.

* TODO This has a link
  :PROPERTIES:
  :ID:       3835d3d0-931a-4a45-a015-a3d6a0baa99a
  :END:
  :BACKLINKS:
  [2020-04-11 Sat 00:26] <- [[id:3835d3d0-931a-4a45-a015-a3d6a0baa99b][This has a link too]]
  :END:

This has a link pointing to the heading above.
**And a backlink, which is a Head related to this one, because both point to the same Test heading target**

[[id:02a5da87-46e5-4ae0-85c1-ee63a570270a][Test heading target]]

* TODO This has a link too
  :PROPERTIES:
  :ID:       3835d3d0-931a-4a45-a015-a3d6a0baa99b
  :END:
  :BACKLINKS:
  [2020-04-11 Sat 00:26] <- [[id:3835d3d0-931a-4a45-a015-a3d6a0baa99a][This has a link]]
  :END:

This has a link pointing to the heading above
**And a backlink, which is a Head related to this one, because both point to the same Test heading target**
[[id:02a5da87-46e5-4ae0-85c1-ee63a570270a][Test heading target]]
```
Could backlinks be created too between second and third Heads, as they are pointing to the same Heading target and so they are related?
This seems a trivial example, but if you have like 20 Headings related with each other, it can be a mess to create a mesh of links and this could be quite elegant solution if is achieved by org-super-links

**Comment by novoid** [comment]
Hi,
Please note that I'm not the owner/maintainer of this repo. I just want to understand.

I'm sorry, I don't get the rationale here. You stated an example and I assume this is the end result of a procecss.

What is the difference between the current default behavior and your idea? Is it that when you use `sl-quick-insert-inline-link` that an additional property backlink is created (that would be different from default behavior) to the direct link?

**Comment by Ypot** [comment]
> I'm sorry, I don't get the rationale here. You stated an example and I assume this is the end result of a process.

It is



> How do you define "related"?

They are notes (nodes) that you want to interlink because they help you to understand a matter.

> What is the difference between the current default behavior and your idea? Is it that when you use `sl-quick-insert-inline-link` that an additional property backlink is created (that would be different from default behavior) to the direct link?
If I am not wrong, that creates just a link and a backlink.

Now imagine that in your file, maybe composed of hundreds of notes (heads), you have 10 "distant" notes (heads) that can help you to understand a matter. How would you interlink each other?
I was thinking in the possibility of having 9 links in each of them, relating in that way the 10 heads. 
This probably should be prompted to the user for each head.

**Comment by toshism** [comment]
If i'm understanding correctly, the way that i handle this is by creating what I call "index" headings. For example if I'm reasearching a topic I will create a somewhat generic "New interesting topic" heading. Then I link all notes to that heading. The end result is i can jump to that heading and have lnks to all topics related to it even though the notes themselves may "belong" to a different tree.

I also do this for things like locations etc. This allows me to take advantage of both hierarchy as well as links. For locations I may have a hierarchy like Germany/Berlin. Then any notes i create that are specifically related to a particular location (restaurants or whatever) I link to the Berlin heading. I like the flexibility of not having to put all things Berlin under the Berlin heading (in this example) because often they are related to something else as well. Maybe a vacation or whatever... I do the same for things like languages, frameworks, projects, etc.

I actually have a custom sidebar I may try to release soon that makes this work pretty well. When you are on a heading you can open the side bar which shows all the incoming and outgoing links to the heading.

**Comment by Ypot** [comment]
> If i'm understanding correctly, the way that i handle this is by creating what I call "index" headings. For example if I'm reasearching a topic I will create a somewhat generic "New interesting topic" heading. Then I link all notes to that heading. The end result is i can jump to that heading and have lnks to all topics related to it even though the notes themselves may "belong" to a different tree.
> 
> I also do this for things like locations etc. This allows me to take advantage of both hierarchy as well as links. For locations I may have a hierarchy like Germany/Berlin. Then any notes i create that are specifically related to a particular location (restaurants or whatever) I link to the Berlin heading. I like the flexibility of not having to put all things Berlin under the Berlin heading (in this example) because often they are related to something else as well. Maybe a vacation or whatever... I do the same for things like languages, frameworks, projects, etc.
> 
> I actually have a custom sidebar I may try to release soon that makes this work pretty well. When you are on a heading you can open the side bar which shows all the incoming and outgoing links to the heading.

I like it, thanks!

I hope to see soon your sidebar, it will be great.

**Comment by novoid** [comment]
Hi @toshism,

> creating what I call "index" headings

You should think of adding such tips to your readme file in a, e.g., "example use-cases" heading or similar. This is a non-technical workflow tip that others might find usable as well as a practical example.

**Comment by Ypot** [comment]
> Hi @toshism,
> 
> > creating what I call "index" headings
> 
> You should think of adding such tips to your readme file in a, e.g., "example use-cases" heading or similar. This is a non-technical workflow tip that others might find usable as well as a practical example.

Very useful tip indeed, but it is pure zettelkasten. Till now I didn't find it useful so I wasn't using it.
