### ISSUE TITLE
Will BACKLINKS drawers be important?

### ISSUE THREAD

**Issue by Ypot** [toshism/org-super-links#27]
I was able to install org-super-links yesterday, now I must do the settings and use it.
Just a question:
Till now I have been doing backlinks manually, but I used no drawer. Do drawers have a function or will have a function in the future? For example, in the coming sidebar, maybe it is important because :BACKLINKS: drawers will be parsed to show the backlinks?

**Comment by toshism** [comment]
Great, I'm glad you got it working. 

Excellent question, and yeah, your intuition is correct. They currently have no function other than display, but the sidebar will make use of (actually require, currently) backlinks to be in a drawer. That's also the reason I'll be releasing it as a separate package.
