### ISSUE TITLE
It would be great to have this on melpa!

### ISSUE THREAD

**Issue by falematte** [toshism/org-super-links#3]

**Comment by toshism** [comment]
I have just a couple of things in the works I would like to complete first in order to get to a more stable state. Then I will see about getting on to melpa. 

Thanks!

**Comment by ykgoon** [comment]
MEPLA please. I use Spacemacs, quelpa doesn't quite work.

**Comment by Ypot** [comment]
I was able to make it run on QUELPA.
Take a look:
https://www.reddit.com/r/orgmode/comments/i1jndg/quelpa_for_dummies/

**Comment by toshism** [comment]
I think this may finally be stable enough I'll try to get it on melpa this week.

**Comment by piater** [comment]
Great! But IMHO #4 should be fixed first.

**Comment by toshism** [comment]
yeah, you are right @piater   I just hate to break everyone’s config/routine at this point. But it will only become harder i suppose.

**Comment by felzix** [comment]
In the interim, can I suggest adding the quelpa installation instructions into the readme? I had to dig into the issues to find an example: `(quelpa '(org-super-links :repo "toshism/org-super-links" :fetcher github))`. Though I now realize you added that to your personal setup example.

**Comment by Ypot** [comment]
> 
> 
> In the interim, can I suggest adding the quelpa installation instructions into the readme? I had to dig into the issues to find an example: `(quelpa '(org-super-links :repo "toshism/org-super-links" :fetcher github))`. Though I now realize you added that to your personal setup example.

Agree. I had to investigate in QUELPA github to get it done.

**Comment by bhankas** [comment]
Since #4 is now closed, is there any other roadblock on way to MELPA?

**Comment by toshism** [comment]
honestly i don't really have the desire to add this to melpa anymore :) i rarely use melpa these days. if someone else wants to go through the process to get it there i'm not opposed though.
