### ISSUE TITLE
Could every link be in a :BACKLINKS: or :LINKS: drawer?

### ISSUE THREAD

**Issue by Ypot** [toshism/org-super-links#31]
Hi
I keep enjoying your package. Just a thought:

Usually when I interlink 2 ideas, none of them is more important than the other. So some times it seems kind of "assymetric" to have a `link `and a `:BACKLINK:`, like if they were different, while they are doing the same function: add a reference to an idea.

Have you thought about the possibility of having all of the links in a drawer called `:LINKS:` or something like that?

```
* TODO Test heading target
  :PROPERTIES:
  :ID:       02a5da87-46e5-4ae0-85c1-ee63a570270a
  :END:
  :LINKS:
  [2020-04-11 Sat 00:26] <- [[id:3835d3d0-931a-4a45-a015-a3d6a0baa99a][This has a link]]
  :END:

This has a link as you can see from the LINKS drawer above.

* TODO This has a link
  :PROPERTIES:
  :ID:       3835d3d0-931a-4a45-a015-a3d6a0baa99a
  :END:

This has a link pointing to the heading above
 :LINKS:
  [2020-04-11 Sat 00:26] <- [[id:02a5da87-46e5-4ae0-85c1-ee63a570270a][Test heading target]]
  :END:
```

**Comment by toshism** [comment]
Yeah sure, you could do that. You can just set it up like this
```
(setq sl-backlink-into-drawer "LINKS"
      sl-related-into-drawer "LINKS")
```
and both links will be in a drawer name "LINKS". if you are concerned about the direction of the `->` being consistent then you'd need to also set `sl-backlink-prefix` or `sl-link-prefix` to match the other.  You could set `sl-backlink-prefix` to `sl-link-prefix-timestamp` or vice versa.

**Comment by Ypot** [comment]
Thanks!
Could it have some incompatibility with the use of coming side bar and other developments of org-super-links?

Right now I am not using prefixes.

**Comment by toshism** [comment]
I _think_ it should be fine. The sidebar will pull the drawer names from your org-super-links configuration. Prefixes won't have any affect.

**Comment by Ypot** [comment]
> 
> 
> Yeah sure, you could do that. You can just set it up like this
> 
> ```
> (setq sl-backlink-into-drawer "LINKS"
>       sl-related-into-drawer "LINKS")
> ```
> 
> and both links will be in a drawer name "LINKS". if you are concerned about the direction of the `->` being consistent then you'd need to also set `sl-backlink-prefix` or `sl-link-prefix` to match the other. You could set `sl-backlink-prefix` to `sl-link-prefix-timestamp` or vice versa.

Backlink now is in the drawer :LINKS:
But inserted link is as always

**Comment by Ypot** [comment]
OK, today everything seems to be working. I can use now :BACKLINKS: and :LINKS: for each type of reference.
Thanks.
