### ISSUE TITLE
Could make "org-super-links sidebar" the using of link descriptions unnecessary? :enhancement:

### ISSUE THREAD

**Issue by Ypot** [toshism/org-super-links#32]
When adding a description to links, if the linked heading is changed, the link will keep working, but the link description will be "obsolete" as it is already different from the heading from which it was created.

If we used just the ID, with no link description, there would be, usually, a lack of information, as the ID commonly is not auto-descriptive.

Could the coming sidebar detect the links in the drawer and show the headings towards they are directed to? In that way we could use the link without description, and watch the information that the heading brings up, always updated. Example:

Notes:
```
* TODO Test heading target
  :PROPERTIES:
  :ID:       02a5da87-46e5-4ae0-85c1-ee63a570270a
  :END:
  :BACKLINKS:
  [2020-04-11 Sat 00:26] <- [[id:3835d3d0-931a-4a45-a015-a3d6a0baa99a]]
  :END:

This has a backlink as you can see from the BACKLINKS drawer above.

* TODO This has a link
  :PROPERTIES:
  :ID:       3835d3d0-931a-4a45-a015-a3d6a0baa99a
  :END:
 :LINKS:
[[id:02a5da87-46e5-4ae0-85c1-ee63a570270a]]
:END:
This has a link pointing to the heading above
```

SIDEBAR 1 for `* TODO Test heading target`:
```
 :BACKLINKS:
TODO This has a link
  :END:
```

SIDEBAR 2 for `* TODO This has a link`:
```
 :LINKS:
TODO Test heading target
:END:
```

**Comment by toshism** [comment]
Yes, It will in fact do exactly that I think. That's if I stay with the current approach i'm using anyway, although I don't quite have it working how i want still, so no guarantees that won't change.
