### ISSUE TITLE
Add link predicates

### ISSUE THREAD

**Issue by konstruktiv** [toshism/org-super-links#35]
There are simple links that do not require a description of the relationship, but it would be very useful to have the _option_ to define the predicate of a (back)link: "instance of", "related to", "member of", or anything else.

For example:
```
* Emacs
:BACKLINKS:
[2020-08-25 Tue 11:23] <- mode of <- [[id:6c54d566-8e54-47a7-9033-16d9220b08ed][Org-Mode]]
:END:
```
One way is to be prompted for the type when adding a link. Another is to define a few valid types and then select the right type when prompted.

**Comment by toshism** [comment]
This is possible by creating a custom `sl-backlink-prefix` function. As a simple example modifying the current backlink prefix function to just prompt for a relationship type something like:

```
(defun sl-backlink-prefix-timestamp-with-predicate ()
  "Return the default prefix string for a backlink.
Inactive timestamp formatted according to `org-time-stamp-formats' and
a separator ' <- '."
  (let* ((time-format (substring (cdr org-time-stamp-formats) 1 -1))
	 (time-stamp (format-time-string time-format (current-time)))
	 (predicate (read-string "Predicate Type: ")))
    (format "[%s] <- %s <- "
	    time-stamp predicate)))
```

Then set `sl-backlink-prefix` like
```
(setq sl-backlink-prefix 'sl-backlink-prefix-timestamp-with-predicate)
```

If you entered `mode of` at the prompt you would end up with something like
```
   :BACKLINKS:
   [2020-08-26 Wed 12:30] <- mode of <- [[id:ba93bf3e-e3eb-4bf6-8646-f64427b2e280][Org-Mode]]
   :END:
```

That's just a quick simple example, you could improve that a lot.

**Comment by konstruktiv** [comment]
That works nicely. I extended it to allow for defined types and completion, using only `LINKS` drawers and changing arrow directions:
```
(setq sl-backlink-into-drawer "LINKS")
(setq sl-related-into-drawer "LINKS")

(setq predicates '("minor mode of" "major mode of"))

(setq sl-backlink-prefix 'sl-backlink-prefix-timestamp-with-predicate)
(defun sl-backlink-prefix-timestamp-with-predicate ()
  (defvar backlink-prefix (let* ((time-stamp (funcall 'sl-backlink-prefix-timestamp))
	 (predicate (ido-completing-read "Predicate: " predicates)))
     (format "%s %s <- " time-stamp predicate)))
     (setq sl-link-prefix (replace-regexp-in-string "<-" "->" backlink-prefix))
  backlink-prefix
)
```
Your package is really nice and it allows for easy extensions such as the above. Do you plan to stick to the core functionality or can you imagine integrating things like predicates?

**Comment by toshism** [comment]
Excellent, and thanks!

As far as the future plans I'm actually a bit undecided at the moment. I had planned to keep it super simple, but there have a been some good ideas lately I hadn't considered. Most likely I think I will end up extracting out the base logic and interface of "linking" two headings out into a separate package and org-mode links (backlink) will simply be one option of the type of link you can create.
