### ISSUE TITLE
Deletion of backlinks

### ISSUE THREAD

**Issue by GPPassos** [toshism/org-super-links#36]
Hi, love the package, thank you for your work!

A suggestion for future enhancement: I feel like it is easy to lose track of the backlinks, since I'd usually just delete a (forward) link by deleting the text directly, but now I'd have a back link with no corresponding forward link. 

I am not sure what would be the best behaviour on this case, but if there was at least a function for checking if any link under that heading still exists, I think it would be useful.

Thanks!

**Comment by toshism** [comment]
Ah yeah, good one. I'll work on it. Thanks!

**Comment by toshism** [comment]
@GPPassos i added this on the `feature/delete-backlinks` branch. i haven’t had time to test it as thoroughly as i want yet, but you can test it there if you’d like. it should be pretty stable. 

i’ll try to get it tested and merged this week.

**Comment by toshism** [comment]
Added, thanks for the suggestion!

**Comment by GPPassos** [comment]
Thank you so much! I will definitely try it out!

**Comment by toshism** [comment]
great thanks. let me know if you have any issues with it.
