### ISSUE TITLE
prefix args do not reach org-capture

### ISSUE THREAD

**Issue by piater** [toshism/org-super-links#39]
Another follow-up to bugs #1 and #2: Any prefix args given to `org-capture` do not reach it. The reason is that the `(interactive)` spec of `sl-store-link` overrides that of the advised function `org-capture`. The fix is simple: Duplicate `org-capture`'s `(interactive "P")` in `sl-store-link`.

**Comment by toshism** [comment]
Awesome. Thanks! I will take a look.

**Comment by toshism** [comment]
fixed. thanks! 

I had never actually used the prefix arg for org-capture but that's really handy. Learned something new today.
