### ISSUE TITLE
Change sl- prefix

### ISSUE THREAD

**Issue by toshism** [toshism/org-super-links#4]
`sl-` is already in use by [sl.el](https://github.com/xuchunyang/sl.el).

Maybe use [names](https://github.com/Malabarba/names) package as org-super-links is a little long.

**Comment by piater** [comment]
How about prefixing everything with `org-sl-`? This is shorter and seems to be in keeping with the conventions. 
I would not add another dependency unless it solves a hard problem.

**Comment by toshism** [comment]
Agreed on the extra dependency. i’m leaning towards just going with the full long name, I think.

**Comment by Ypot** [comment]
Maybe we could use that joke too, or could it be confusing?
> 
> 
> SL (Steam Locomotive) runs across your terminal when you type "sl" as you meant to type "ls". It's just a joke command, and not useful at all.**

I have installed sl BTW ;D

**Comment by vv111y** [comment]
+1 for @piater suggestion `org-sl-`

**Comment by toshism** [comment]
I've (finally) made the change to rename everything `sl-` to `org-super-links-` so we can get this on melpa. If anyone could test it that would be great. it's currently on the `melpa-fixes` branch.

https://github.com/toshism/org-super-links/tree/melpa-fixes 

see also #3

**Comment by toshism** [comment]
done in PR #52
