### ISSUE TITLE
Bug after updating emacs?

### ISSUE THREAD

**Issue by Ypot** [toshism/org-super-links#44]
Hi

It seems that after updating to emacs 27.1 the :LINK: drawer is not generated in the heading where you hit "sl-store-link".

Edit: It seems the drawer is not created in one of my buffers, independently if I hit "sl-store-link" or "sl-insert-link" on it.
Edit 2: Now it works, same buffer, different heading.

**Comment by toshism** [comment]
Hey, could you provide any details about the heading it's not working for? Especially the drawers and other properties etc. I'd like to investigate if there could be some particular formatting that causes an issue.

thanks!

**Comment by Ypot** [comment]
> 
> 
> Hey, could you provide any details about the heading it's not working for? Especially the drawers and other properties etc. I'd like to investigate if there could be some particular formatting that causes an issue.
> 
> thanks!

I can't reproduce the behaviour. If it is repeated I will let you know.
BTW there is something annoying which always happens:
In the drawer, the :END: appears as not recognized. I have to go to it and hit ENTER or write and delete a blank space. See:

https://i.ibb.co/xsgS4j1/Captura.jpg

https://i.ibb.co/HhLK1Nm/Captura.jpg

**Comment by toshism** [comment]
I actually have this same problem. You can even see it in the screen shots in the readme. I had just sort of written it off as something with my theme because it doesn't affect functionality for me. Thanks for letting me know. I'll look into it now. :) 

You can open a bug about this too.
