### ISSUE TITLE
Inserting a link with org-rifle breaks the target file

### ISSUE THREAD

**Issue by volhovm** [toshism/org-super-links#48]
So assume you have two files, `FS` and `FT`, and I'm trying to reference the header `T` (in `FT`) from header `S` (in `FS`) using org-rifle (the issue is the same with org-ql). That is, I expect that while standing inside `S` I call `sl-link`, select `T` and together with a forward link to `T` there is a backlink in `T` created that points to `S`. Now, the issue is the following:

Whenever my (inactive) pointer in `FT` is, say, position `F`, the call described will:
1. Insert a backlink in `T` to `S`, but without a newline at the end
2. Return back to the place in `FT`, insert a newline there, and forward link `S` to _this_ place (header at `F`).

I managed to trace down the issue to the `org-insert-link` call in `sl-insert-backlink`. What happens, somehow, is that after this function inserts the link, it jumps to the previous position in `FT` and inserts a newline _there_ (at `F`), instead of just inserting it after the link. I don't know a way to prevent `org-insert-link` from doing so, and I don't understand why this happens, since `org-insert-link` is a huge function. Wrapping `sl-insert-backlink` in `save-excursion` also doesn't really help.

I also thought it could be somehow related to `org-make-link-description-function`, which was deprecated?

I'm really bad at elisp, and I would be really helpful to hear any feedback on this, (I like the library idea a lot!). 

PS: in `org-super-links-org-rifle.el` there's a typo (`helm-org-ql` when it should be `helm-org-rifle`) which prevents the rifle action from being turned on.
```
(with-eval-after-load "helm-org-ql"
  (add-to-list 'helm-org-rifle-actions '("Super Link" . sl-insert-link-rifle-action) t)
```

**Comment by toshism** [comment]
Interesting, do you get a line return in both positions (target and source) or only at `FT`? Can you try setting `sl-backlink-postfix` to some string to test if the line return is truly coming from `org-insert-link` or if it's `sl-insert-backlink` setting it in the wrong place?


> PS: in `org-super-links-org-rifle.el` there's a typo (`helm-org-ql` when it should be `helm-org-rifle`) which prevents the rifle action from being turned on.
> 
> ```
> (with-eval-after-load "helm-org-ql"
>   (add-to-list 'helm-org-rifle-actions '("Super Link" . sl-insert-link-rifle-action) t)
> ```

well that's embarassing. thanks.

**Comment by volhovm** [comment]
I've been playing with the source code for a while, so I'm pretty sure it's `org-insert-link` and not anything else. When I replace `org-insert-link` call by `(insert "BLA")`, it works perfectly well: in `FT` it goes to `T`, inserts a backlink `[DATE] <- BLA` on the top of the list, and returns the point in `FT` after that back to `F`. 

But somehow `org-insert-link` adds an extra newline... and jumps to the previous point location before that!

Here's a minimal example that I find a bit strange:
```
(defun sl-insert-backlink-minexample ()
  (interactive)
  (let* ((org-log-into-drawer (sl-backlink-into-drawer))
         (beg (org-log-beginning t)))
    (goto-char beg)
    (call-interactively 'org-insert-last-stored-link)
  ))

(global-set-key (kbd "C-c r") 'sl-insert-backlink-minexample)
```
When I `org-store-link` any header `S`, and then go to `T`, this function inserts the link to the header `S` in `T`'s `BACKLINKS` on top of the list, _and adds a newline_, although notice that this is supposed to be done by `(insert (sl-backlink-postfix))` in the original function. Is this expected?

**Comment by toshism** [comment]
Yeah, strange. I'm actually not sure exactly what is happening there. I will have to look into it a bit. Thanks for the investigation.

**Comment by volhovm** [comment]
My config is essentially empty, I just load the package from quelpa (or locally), and use it. As I said before, `org-make-link-description-function` is `nil` for me, since 
```
  This variable is an alias for ‘org-link-make-description-function’.
  This variable is obsolete since Org 9.3;
  use ‘org-link-make-description-function’ instead.
```

Thanks!

**Comment by toshism** [comment]
I had a litle time to look into this a bit finally. I can recreate it now under a specific circumstance, but I haven't had any luck debugging it yet. I'm only able to reliably recreate it if i call `sl-link` from within an active capture. In this case the ending line return gets added to the point from where capture was originally called. But if I step through `org-insert-link` with edebug it doesn't fail and works as expected. without the debugger it fails... strange.

**Comment by toshism** [comment]
I refactored `sl-insert-backlink` and `sl--insert-link` function (now known as `org-super-links-insert-backlink` and `org-super-links--insert-link`) which should fix this issue. Feel free to reopen if you have any more issues.

**Comment by volhovm** [comment]
Thanks, seems to work for me.

The only minor thing I noticed is a typo here: https://github.com/toshism/org-super-links/blob/develop/org-super-links-org-rifle.el#L35, this should be `org-super-links-org-rifle-insert-link-action` (without the second `rifle`).

**Comment by toshism** [comment]
Well, obviously I do not use rifle. Sorry about that, and thanks for checking. It's fixed now.
