### ISSUE TITLE
:END: Problem: "Anti-bug" discovered

### ISSUE THREAD

**Issue by Ypot** [toshism/org-super-links#57]
Good night, dear toshism

Time ago a problem goes after us: in the :LINKS: drawer the :END: is like not recognized and we have to go and modify it by hand.
Tonight using your package, as usual, I discovered an "anti-bug" that makes the :END: in the drawer to appear correctly and I thought that maybe it could help you to understand how to solve the problem:

If the body of a note starts with an `/italic/` word, the :END: is added correctly when creating the link.

```
* Note
/here/ the :END: in the drawer works as intended
```

**Comment by toshism** [comment]
That's strange.... thanks for the tip. I'll try to look into this at some point.

**Comment by Ypot** [comment]
I am now trying to reproduce the "antibug" and it seems to work just if PROPERTIES already exist. I suppose it will not be easy to reproduce.
