### ISSUE TITLE
org-super-links-convert-link-to-super fails when org-super-links-related-into-drawer is nil

### ISSUE THREAD

**Issue by dalanicolai** [toshism/org-super-links#58]
Just checking out your package because I am working on "updating/modernizing" [org-wiki](https://github.com/caiorss/org-wiki) to make it work more like [zim](https://zim-wiki.org/) (you can find my fork [here](https://github.com/dalanicolai/org-wiki), but I am just starting, so there is still a lot to be done, for which I will probably take my time). Anyway, I wanted to implement some (enhanced) backlink functionality, and then I found this package which looks very useful.

Anyway, I am just starting checking it out, and I noticed that when trying to `org-super-links-convert-link-to-super` (without `C-u`) with `org-super-links-related-into-drawer` is `nil` then the formatting of the original link breaks.
Simply the new link format gets inserted, while the original link does not get deleted. To fix it the original link should get deleted before the `(org-super-links--insert-link target arg)`. in the `org-super-links-convert-link-to-super` function.

Anyway, thanks for your very nice package!

**Comment by toshism** [comment]
@dalanicolai this should be fixed in current develop branch now. Let me know if you still have any problems.
