### ISSUE TITLE
`org-super-links-convert-link-to-super` re-inserts the current link at point

### ISSUE THREAD

**Issue by NightMachinery** [toshism/org-super-links#59]
![image](https://user-images.githubusercontent.com/36224762/117564709-a39c3700-b0c2-11eb-8642-8749a5af8d9a.png)

Calling `org-super-links-convert-link-to-super`:
![image](https://user-images.githubusercontent.com/36224762/117564718-b1ea5300-b0c2-11eb-97b5-e45ef17bf91f.png)

`org-super-links-related-into-drawer` is `nil`, if it matters. I also just installed from the develop branch, so the code should be at the latest commit.

**Comment by toshism** [comment]
@NightMachinary this should be fixed in develop branch now. Let me know if you still have any problems.
