### ISSUE TITLE
Message when installing using QUELPA

### ISSUE THREAD

**Issue by Ypot** [toshism/org-super-links#63]
I receive this message. Is it important?
```
In end of data:
org-super-links.el:442:1:Warning: the function `org-refile-get-location' is
    not known to be defined.
```
Command:
`(quelpa '(org-super-links :repo "toshism/org-super-links" :fetcher github))`

**Comment by felzix** [comment]
My guess is your org version is old. I don't know if it's a problem or not.

**Comment by toshism** [comment]
I'm not exactly sure why you get that. `org-refile-get-location` is part of default org though, so it shouldn't cause any problem. 

It's also only used if you do not use `helm-org-ql` or `helm-org-rifle` for your search function.
