### ISSUE TITLE
insert link got error "Wrong type argument: stringp, nil"

### ISSUE THREAD

**Issue by re-f** [toshism/org-super-links#66]
the debug info:
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  set-buffer(nil)
  (save-current-buffer (set-buffer (marker-buffer marker)) (save-excursion (goto-char (marker-position marker)) (run-hooks hooks) (call-interactively 'org-store-link) (car-safe (prog1 org-stored-links (setq org-stored-links (cdr org-stored-links))))))
  org-super-links-links-action(#<marker in no buffer> org-super-links-pre-backlink-hook)
  (let* ((source (point-marker)) (source-link (org-super-links-links-action source 'org-super-links-pre-link-hook)) (target-link (org-super-links-links-action target 'org-super-links-pre-backlink-hook)) (source-formatted-link (org-super-links-link-builder source-link)) (target-formatted-link (org-super-links-link-builder target-link))) (save-current-buffer (set-buffer (marker-buffer target)) (save-excursion (goto-char (marker-position target)) (if (derived-mode-p 'org-mode) (progn (org-super-links-insert-backlink (car source-formatted-link) (cdr source-formatted-link)))))) (if no-forward nil (save-current-buffer (set-buffer (marker-buffer source)) (save-excursion (goto-char (marker-position source)) (org-super-links-insert-relatedlink (car target-formatted-link) (cdr target-formatted-link))))))
  org-super-links--insert-link(#<marker in no buffer>)
  (let ((target (org-refile-get-location "Super Link"))) (org-super-links--insert-link (set-marker (make-marker) (car (cdr (cdr (cdr target)))) (get-file-buffer (car (cdr target))))))
  org-super-links-get-location()
  funcall(org-super-links-get-location)
  (cond ((string= org-super-links-search-function "helm-org-ql") (require 'org-super-links-org-ql) (org-super-links-org-ql-link-search-interface)) ((string= org-super-links-search-function "helm-org-rifle") (require 'org-super-links-org-rifle) (org-super-links-org-rifle-link-search-interface)) (t (funcall org-super-links-search-function)))
  org-super-links-search-function()
  org-super-links-link()
  (let ((org-super-links-related-into-drawer nil) (org-super-links-link-prefix nil)) (org-super-links-link))
  org-super-links-quick-insert-inline-link()
  funcall-interactively(org-super-links-quick-insert-inline-link)
  call-interactively(org-super-links-quick-insert-inline-link record nil)
  #f(compiled-function (cmd &optional record-flag keys special) "Execute CMD as an editor command.\nCMD must be a symbol that satisfies the `commandp' predicate.\nOptional second arg RECORD-FLAG non-nil\nmeans unconditionally put this command in the variable `command-history'.\nOtherwise, that is done only if an arg is read using the minibuffer.\nThe argument KEYS specifies the value to use instead of (this-command-keys)\nwhen reading the arguments; if it is nil, (this-command-keys) is used.\nThe argument SPECIAL, if non-nil, means that this command is executing\na special event, so ignore the prefix argument and don't clear it." #<bytecode 0x404ec17b>)(org-super-links-quick-insert-inline-link record nil nil)
  ad-Advice-command-execute(#f(compiled-function (cmd &optional record-flag keys special) "Execute CMD as an editor command.\nCMD must be a symbol that satisfies the `commandp' predicate.\nOptional second arg RECORD-FLAG non-nil\nmeans unconditionally put this command in the variable `command-history'.\nOtherwise, that is done only if an arg is read using the minibuffer.\nThe argument KEYS specifies the value to use instead of (this-command-keys)\nwhen reading the arguments; if it is nil, (this-command-keys) is used.\nThe argument SPECIAL, if non-nil, means that this command is executing\na special event, so ignore the prefix argument and don't clear it." #<bytecode 0x404ec17b>) org-super-links-quick-insert-inline-link record)
  apply(ad-Advice-command-execute #f(compiled-function (cmd &optional record-flag keys special) "Execute CMD as an editor command.\nCMD must be a symbol that satisfies the `commandp' predicate.\nOptional second arg RECORD-FLAG non-nil\nmeans unconditionally put this command in the variable `command-history'.\nOtherwise, that is done only if an arg is read using the minibuffer.\nThe argument KEYS specifies the value to use instead of (this-command-keys)\nwhen reading the arguments; if it is nil, (this-command-keys) is used.\nThe argument SPECIAL, if non-nil, means that this command is executing\na special event, so ignore the prefix argument and don't clear it." #<bytecode 0x404ec17b>) (org-super-links-quick-insert-inline-link record))
  command-execute(org-super-links-quick-insert-inline-link record)
  counsel-M-x-action("org-super-links-quick-insert-inline-link")
  #f(compiled-function (x) #<bytecode 0xa9365b4b>)("org-super-links-quick-insert-inline-link")
  ivy-call()
  #f(compiled-function (arg1 arg2 &rest rest) "Read a string in the minibuffer, with completion.\n\nPROMPT is a string, normally ending in a colon and a space.\n`ivy-count-format' is prepended to PROMPT during completion.\n\nCOLLECTION is either a list of strings, a function, an alist, or\na hash table, supplied for `minibuffer-completion-table'.\n\nPREDICATE is applied to filter out the COLLECTION immediately.\nThis argument is for compatibility with `completing-read'.\n\nWhen REQUIRE-MATCH is non-nil, only members of COLLECTION can be\nselected.\n\nIf INITIAL-INPUT is non-nil, then insert that input in the\nminibuffer initially.\n\nHISTORY is a name of a variable to hold the completion session\nhistory.\n\nKEYMAP is composed with `ivy-minibuffer-map'.\n\nPRESELECT, when non-nil, determines which one of the candidates\nmatching INITIAL-INPUT to select initially.  An integer stands\nfor the position of the desired candidate in the collection,\ncounting from zero.  Otherwise, use the first occurrence of\nPRESELECT in the collection.  Comparison is first done with\n`equal'.  If that fails, and when applicable, match PRESELECT as\na regular expression.\n\nDEF is for compatibility with `completing-read'.\n\nUPDATE-FN is called each time the candidate list is re-displayed.\n\nWhen SORT is non-nil, `ivy-sort-functions-alist' determines how\nto sort candidates before displaying them.\n\nACTION is a function to call after selecting a candidate.\nIt takes one argument, the selected candidate. If COLLECTION is\nan alist, the argument is a cons cell, otherwise it's a string.\n\nMULTI-ACTION, when non-nil, is called instead of ACTION when\nthere are marked candidates. It takes the list of candidates as\nits only argument. When it's nil, ACTION is called on each marked\ncandidate.\n\nUNWIND is a function of no arguments to call before exiting.\n\nRE-BUILDER is a function transforming input text into a regex\npattern.\n\nMATCHER is a function which can override how candidates are\nfiltered based on user input.  It takes a regex pattern and a\nlist of candidates, and returns the list of matching candidates.\n\nDYNAMIC-COLLECTION is a boolean specifying whether the list of\ncandidates is updated after each input by calling COLLECTION.\n\nEXTRA-PROPS is a plist that can be used to store\ncollection-specific session-specific data.\n\nCALLER is a symbol to uniquely identify the caller to `ivy-read'.\nIt is used, along with COLLECTION, to determine which\ncustomizations apply to the current completion session." #<bytecode 0xa8ac640b>)("M-x " ("org-super-links-quick-insert-inline-link" "org-super-links-insert-link" "org-super-links-link" "org-roam-insert" "org-super-links-store-link" "org-super-links-quick-insert-drawer-link" "org-mark-ring-goto" "org-store-link" "balance-windows" "persp-switch" "org-insert-drawer" "org-edit-src-code" "org-archive-subtree" "goto-last-change" "avy-goto-word-1" "avy-goto-word-0" "org-id-goto" "org-cut-subtree" "color-rg-replace-all-matches" "pyim-punctuation-toggle" "org-sidebar-tree" "org-attach" "org-agenda-columns" "org-content" "package-install" "org-toggle-inline-images" "package-refresh-contents" "org-set-property" "xah-open-in-vscode" "org-roam-server-mode" "dired-omit-mode" "multiple-cursors-mode" "list-packages" "mc/mark-next-like-this-word" "org-refile-goto-last-stored" "keyfreq-show" "org-demote-subtree" "org-html-export-to-html" "dired" "magit" "read-only-mode" "org-roam-capture" "cns-mode" "org-copy-subtree" "org-sidebar-toggle" "rg-dwim-current-dir" "org-insert-structure-template" "focus-mode" "org-sidebar" "global-cns-mode" ...) :predicate counsel--M-x-externs-predicate :require-match t :history counsel-M-x-history :action counsel-M-x-action :keymap (keymap (67108908 . counsel--info-lookup-symbol) (67108910 . counsel-find-symbol)) :initial-input nil :caller counsel-M-x :sort t)
  apply(#f(compiled-function (arg1 arg2 &rest rest) "Read a string in the minibuffer, with completion.\n\nPROMPT is a string, normally ending in a colon and a space.\n`ivy-count-format' is prepended to PROMPT during completion.\n\nCOLLECTION is either a list of strings, a function, an alist, or\na hash table, supplied for `minibuffer-completion-table'.\n\nPREDICATE is applied to filter out the COLLECTION immediately.\nThis argument is for compatibility with `completing-read'.\n\nWhen REQUIRE-MATCH is non-nil, only members of COLLECTION can be\nselected.\n\nIf INITIAL-INPUT is non-nil, then insert that input in the\nminibuffer initially.\n\nHISTORY is a name of a variable to hold the completion session\nhistory.\n\nKEYMAP is composed with `ivy-minibuffer-map'.\n\nPRESELECT, when non-nil, determines which one of the candidates\nmatching INITIAL-INPUT to select initially.  An integer stands\nfor the position of the desired candidate in the collection,\ncounting from zero.  Otherwise, use the first occurrence of\nPRESELECT in the collection.  Comparison is first done with\n`equal'.  If that fails, and when applicable, match PRESELECT as\na regular expression.\n\nDEF is for compatibility with `completing-read'.\n\nUPDATE-FN is called each time the candidate list is re-displayed.\n\nWhen SORT is non-nil, `ivy-sort-functions-alist' determines how\nto sort candidates before displaying them.\n\nACTION is a function to call after selecting a candidate.\nIt takes one argument, the selected candidate. If COLLECTION is\nan alist, the argument is a cons cell, otherwise it's a string.\n\nMULTI-ACTION, when non-nil, is called instead of ACTION when\nthere are marked candidates. It takes the list of candidates as\nits only argument. When it's nil, ACTION is called on each marked\ncandidate.\n\nUNWIND is a function of no arguments to call before exiting.\n\nRE-BUILDER is a function transforming input text into a regex\npattern.\n\nMATCHER is a function which can override how candidates are\nfiltered based on user input.  It takes a regex pattern and a\nlist of candidates, and returns the list of matching candidates.\n\nDYNAMIC-COLLECTION is a boolean specifying whether the list of\ncandidates is updated after each input by calling COLLECTION.\n\nEXTRA-PROPS is a plist that can be used to store\ncollection-specific session-specific data.\n\nCALLER is a symbol to uniquely identify the caller to `ivy-read'.\nIt is used, along with COLLECTION, to determine which\ncustomizations apply to the current completion session." #<bytecode 0xa8ac640b>) ("M-x " ("org-super-links-quick-insert-inline-link" "org-super-links-insert-link" "org-super-links-link" "org-roam-insert" "org-super-links-store-link" "org-super-links-quick-insert-drawer-link" "org-mark-ring-goto" "org-store-link" "balance-windows" "persp-switch" "org-insert-drawer" "org-edit-src-code" "org-archive-subtree" "goto-last-change" "avy-goto-word-1" "avy-goto-word-0" "org-id-goto" "org-cut-subtree" "color-rg-replace-all-matches" "pyim-punctuation-toggle" "org-sidebar-tree" "org-attach" "org-agenda-columns" "org-content" "package-install" "org-toggle-inline-images" "package-refresh-contents" "org-set-property" "xah-open-in-vscode" "org-roam-server-mode" "dired-omit-mode" "multiple-cursors-mode" "list-packages" "mc/mark-next-like-this-word" "org-refile-goto-last-stored" "keyfreq-show" "org-demote-subtree" "org-html-export-to-html" "dired" "magit" "read-only-mode" "org-roam-capture" "cns-mode" "org-copy-subtree" "org-sidebar-toggle" "rg-dwim-current-dir" "org-insert-structure-template" "focus-mode" "org-sidebar" "global-cns-mode" ...) :predicate counsel--M-x-externs-predicate :require-match t :history counsel-M-x-history :action counsel-M-x-action :keymap (keymap (67108908 . counsel--info-lookup-symbol) (67108910 . counsel-find-symbol)) :initial-input nil :caller counsel-M-x :sort t))
  ivy-read("M-x " ("org-super-links-quick-insert-inline-link" "org-super-links-insert-link" "org-super-links-link" "org-roam-insert" "org-super-links-store-link" "org-super-links-quick-insert-drawer-link" "org-mark-ring-goto" "org-store-link" "balance-windows" "persp-switch" "org-insert-drawer" "org-edit-src-code" "org-archive-subtree" "goto-last-change" "avy-goto-word-1" "avy-goto-word-0" "org-id-goto" "org-cut-subtree" "color-rg-replace-all-matches" "pyim-punctuation-toggle" "org-sidebar-tree" "org-attach" "org-agenda-columns" "org-content" "package-install" "org-toggle-inline-images" "package-refresh-contents" "org-set-property" "xah-open-in-vscode" "org-roam-server-mode" "dired-omit-mode" "multiple-cursors-mode" "list-packages" "mc/mark-next-like-this-word" "org-refile-goto-last-stored" "keyfreq-show" "org-demote-subtree" "org-html-export-to-html" "dired" "magit" "read-only-mode" "org-roam-capture" "cns-mode" "org-copy-subtree" "org-sidebar-toggle" "rg-dwim-current-dir" "org-insert-structure-template" "focus-mode" "org-sidebar" "global-cns-mode" ...) :predicate counsel--M-x-externs-predicate :require-match t :history counsel-M-x-history :action counsel-M-x-action :keymap (keymap (67108908 . counsel--info-lookup-symbol) (67108910 . counsel-find-symbol)) :initial-input nil :caller counsel-M-x)
  counsel-M-x()
  funcall-interactively(counsel-M-x)
  call-interactively(counsel-M-x nil nil)
  #f(compiled-function (cmd &optional record-flag keys special) "Execute CMD as an editor command.\nCMD must be a symbol that satisfies the `commandp' predicate.\nOptional second arg RECORD-FLAG non-nil\nmeans unconditionally put this command in the variable `command-history'.\nOtherwise, that is done only if an arg is read using the minibuffer.\nThe argument KEYS specifies the value to use instead of (this-command-keys)\nwhen reading the arguments; if it is nil, (this-command-keys) is used.\nThe argument SPECIAL, if non-nil, means that this command is executing\na special event, so ignore the prefix argument and don't clear it." #<bytecode 0x404ec17b>)(counsel-M-x nil nil nil)
  ad-Advice-command-execute(#f(compiled-function (cmd &optional record-flag keys special) "Execute CMD as an editor command.\nCMD must be a symbol that satisfies the `commandp' predicate.\nOptional second arg RECORD-FLAG non-nil\nmeans unconditionally put this command in the variable `command-history'.\nOtherwise, that is done only if an arg is read using the minibuffer.\nThe argument KEYS specifies the value to use instead of (this-command-keys)\nwhen reading the arguments; if it is nil, (this-command-keys) is used.\nThe argument SPECIAL, if non-nil, means that this command is executing\na special event, so ignore the prefix argument and don't clear it." #<bytecode 0x404ec17b>) counsel-M-x)
  apply(ad-Advice-command-execute #f(compiled-function (cmd &optional record-flag keys special) "Execute CMD as an editor command.\nCMD must be a symbol that satisfies the `commandp' predicate.\nOptional second arg RECORD-FLAG non-nil\nmeans unconditionally put this command in the variable `command-history'.\nOtherwise, that is done only if an arg is read using the minibuffer.\nThe argument KEYS specifies the value to use instead of (this-command-keys)\nwhen reading the arguments; if it is nil, (this-command-keys) is used.\nThe argument SPECIAL, if non-nil, means that this command is executing\na special event, so ignore the prefix argument and don't clear it." #<bytecode 0x404ec17b>) counsel-M-x)
  command-execute(counsel-M-x)

**Comment by toshism** [comment]
hmm... that's a lot. can you describe what you were doing when it happened? does it continue to happen? does it happen everytime?
