### ISSUE TITLE
Generate CUSTOM-ID on link creation

### ISSUE THREAD

**Issue by nmartin84** [toshism/org-super-links#7]
It would be nice if sl-store and sl-insert would generate a custom-id for the entries. When exporting to HTML the backlink is broken.

**Comment by toshism** [comment]
this is what i use:

```
(require ‘org-id)
(setq org-id-link-to-org-use-id 'create-if-interactive-and-no-custom-id)
```

that will auto add a unique id to both headings any time you add a link.

org-id is included with org-mode. 

let me know if that works for your workflow. i don’t use html export so i can’t say for sure how it works, but i expect it should work fine.

**Comment by nmartin84** [comment]
Well org-id would work fine if I was using it inside of emacs only, but it breaks on HTML exports. I'm publishing a lot of my notes for others to use and I tend to take a lot of notes that may refer back to a central topic, so the back links is a great feature. But I need superlinks to generate the custom-id when it captures or inserts a link so they work on HTML exports.

**Comment by nmartin84** [comment]
This may get me by until I figure a way to make superlinks generate the custom-id.
https://writequit.org/articles/emacs-org-mode-generate-ids.html

**Comment by toshism** [comment]
ah, so you need custom-id specifically and not id?

**Comment by nmartin84** [comment]
Exactly, similar to this piece of code that uses rifle actions. 

```
  (defun helm-org-rifle--store-link (candidate &optional use-custom-id)
    "Store a link to CANDIDATE."
    (-let (((buffer . pos) candidate))
      (with-current-buffer buffer
        (org-with-wide-buffer
         (goto-char pos)
         (when (and use-custom-id
                    (not (org-entry-get nil "CUSTOM_ID")))
           (org-set-property "CUSTOM_ID"
                             (read-string (format "Set CUSTOM_ID for %s: "
                                                  (substring-no-properties
                                                   (org-format-outline-path
                                                    (org-get-outline-path t nil))))
                                          (helm-org-rifle--make-default-custom-id
                                           (nth 4 (org-heading-components))))))
         (call-interactively 'org-store-link)))))
```

**Comment by toshism** [comment]
Ok, i'm with you now. I'll think about it a bit to see if there is a non-obtrusive way to support this. 

In the mean time if you want to take a look, you should probably look at the `sl--insert-link` function. There are two calls to `org-store-link` there. The first one is called with the point on the side where the link will go, the second is called on the side where the backlink will go.

**Comment by nmartin84** [comment]
Thanks! Will do. I did come across another issue with sl-insert-backlink. It was using the full file path regardless and not respecting org-link-file-path-type. I was able to get it working correctly by using org-insert-last-link. I'll play with the insert-link function and see if I can get custom-id's working.

**Comment by toshism** [comment]
i should add, i released a new version last night that includes some refactoring around the link insertion, so you should probably update before digging too deep.

**Comment by toshism** [comment]
> I did come across another issue with sl-insert-backlink. It was using the full file path regardless and not respecting org-link-file-path-type.

I would consider this a bug. I'd prefer it respects as much of the default org functionality as possible.

I will get a fix going for that.

**Comment by nmartin84** [comment]
Good deal, I haven't had time to play with this yet but we can probably consider this closed. I'll add something if I get this to work.

**Comment by toshism** [comment]
@nmartin84 I added a couple of hooks you can use to handle this now.

Just using the `eos/org-custom-id-get` function in the example you linked you can now just do something along these lines.

```
(defun sl-add-custom-id ()
  (eos/org-custom-id-get nil t))

(add-hook 'sl-pre-link-hook 'sl-custom-id)
(add-hook 'sl-pre-backlink-hook 'sl-custom-id)
```

and both link side and backlink side will get a custom id set based on the `eos/org-custom-id-get` function.

**Comment by nmartin84** [comment]
Looks great!! Thanks man!
