### ISSUE TITLE
[Suggestion] Non fontification in links

### ISSUE THREAD

**Issue by Ypot** [toshism/org-super-links#71]
Could the links be created without fontification?

For example, if I have this headline:
`* _super-links_ by *toshism*!`

The link would be like:
`[[id:20220605T175122.000000][_super-links_ by *toshism*!]]`

For a link I think fontification doesn't help, I would prefer:
`[[id:20220605T175122.000000][super-links by toshism!]]`

Is it possible?

**Comment by toshism** [comment]
Hey @Ypot, this is possible currently, but is not the default behavior. Default is to leave descriptions untouched. See here for an example of how to implement something like this though. https://github.com/toshism/org-super-links/issues/25
