### ISSUE TITLE
Can't install with the instructions provided

### ISSUE THREAD

**Issue by davidromerot** [toshism/org-super-links#72]
The installation instructions, which rely on `use-package`, do not work. The package is not found on MELPA, ELPA or the non-GNU ELPA.
How do you install it? Can anyone provide instructions?

Thanks!

**Comment by toshism** [comment]
Ah yes, sorry about that. I switched to using [straight](https://github.com/radian-software/straight.el) and kind of dropped the ball on getting this onto melpa. 

It's easy with straight, or you can also use quelpa. there are instructions for installing with quelpa [here](https://github.com/toshism/org-super-links/blob/65bc010db8f9f6f992030e508d356bcb7743d700/README.org#installation).

I will at least update the readme with proper instructions. thanks for reminding me.
