### ISSUE TITLE
link-prefix-timestamp broken (since org 9.6)

### ISSUE THREAD

**Issue by stefan2904** [toshism/org-super-links#79]
Hi there!

After upgrading to the newest org-mode, I noticed that backlinks and related-links are broken:

```
:RELATED:
[Y-12-12 Mon 22:%] -> [[id:ef059713-6771-460f-a405-de0a0b571854][Fix orgmode ...]]
:END:
:BACKLINKS:
[Y-12-12 Mon 22:%] <- [[id:ef059713-6771-460f-a405-de0a0b571854][Fix orgmode ...]]
:END:
```

---

I did some digging, and I think I figured out why:

The org-sl function responsible for creating the prefix is [`org-super-links-link-prefix-timestamp`](https://github.com/toshism/org-super-links/blob/a48da417cfe448616b2ef494ac26fe4d5816f811/org-super-links.el#L274-L281), so if we run that one directly we can reproduce the result (for convenience I copied the function):

``` emacs-lisp
(defun org-super-links-link-prefix-timestamp ()
  "Return the default prefix string for a backlink.
Inactive timestamp formatted according to `org-time-stamp-formats' and
a separator ' -> '."
  (let* ((time-format (substring (cdr org-time-stamp-formats) 1 -1))
	 (time-stamp (format-time-string time-format (current-time))))
    (format "[%s] -> "
	    time-stamp)))

(org-super-links-link-prefix-timestamp)
```

> #+RESULTS:
> : [Y-12-12 Mon 22:%] ->

The issue is that it does a substring on (the first value of) `org-time-stamp-formats`. I guess this was to remove the leading/trailing `<>` sign. [In a org commit](https://git.savannah.gnu.org/cgit/emacs/org-mode.git/commit/lisp/org.el?id=e3a7c01874) (which is part of org 9.6) the value of `org-time-stamp-formats` was changed, _stripping leading "<" and trailing ">"_. So instead, your function is now removing the first and last character of the format-string:

``` emacs-lisp
(substring (cdr org-time-stamp-formats) 1 -1)
```

> #+RESULTS:
> : Y-%m-%d %a %H:%

**Comment by stefan2904** [comment]
I have some code in some snippet that removes the brackets only if they exist, maybe a fix can build on that:

```elisp
(replace-regexp-in-string "\\[\\(.*\\)\\]" "<\\1>" (symbol-value 'org-last-inserted-timestamp))
```
(this replaces [] with <>, but you get the idea)

Disclaimer: I am not a elisp programmer ;-)

**Comment by stefan2904** [comment]
Something like this:

``` emacs-lisp
(replace-regexp-in-string "<\\(.*\\)>" "\\1" (cdr org-time-stamp-formats))
```

> #+RESULTS:
> : %Y-%m-%d %a %H:%M

Test org 9.6:

``` emacs-lisp
(replace-regexp-in-string "<\\(.*\\)>" "\\1" "%Y-%m-%d %a %H:%M")
```

> #+RESULTS:
> : %Y-%m-%d %a %H:%M

Test older org (I guess):

``` emacs-lisp
(replace-regexp-in-string "<\\(.*\\)>" "\\1" "<%Y-%m-%d %a %H:%M>")
```

> #+RESULTS:
> : %Y-%m-%d %a %H:%M

Or just hardcode your own formatstring?

**Comment by toshism** [comment]
Hey, thanks for the research! I'm guessing this is related to https://github.com/toshism/org-super-links/pull/78 from @akirak . I've been meaning to test it but have been a bit busy. I'll try to make sure and get that tested and merged soon!

If someone else wants to validate it with 9.6 and and older version that would be great too.

**Comment by stefan2904** [comment]
Ach, I checked the existing issues but missed the open PR. ;-) Looks like it's the same problem, yes. Great that there is already a fix. 

The use of the function to retrieve the format string looks the way to go, nice. I'll test it when I find time.

**Comment by stefan2904** [comment]
I did some tests, see my comments in #78 for the results.

For reference here is the infra code I used to test it: 
https://gist.github.com/stefan2904/85cff4c12a1e0e07e3ddd4a822711c39

Not sure why I did it in docker, probably `emacs -Q` would have been enough. :shrug:

**Comment by toshism** [comment]
Awesome, thanks for the testing! merged
