### ISSUE TITLE
Customizable link descriptions using properties

### ISSUE THREAD

**Issue by Ypot** [toshism/org-super-links#83]
Could link description be taken from properties?

```
* Headline
  :PROPERTIES:
  :title:       Book title
  :author:   John Smith
  :data:       1984
  :END:
** Chapter 1
Linked chapter

* Notes to the book
Link description: John Smith (1984). Book title. /Chapter 1/.
```

**Comment by toshism** [comment]
yeah it could be, you can set a custom function for `org-super-links-default-description-formatter`. basically that function will get a link as an argument, you can follow it and grab whatever info you need to return.

**Comment by toshism** [comment]
i'm going to close this but let me know if you have any questions about the formatter.
