### ISSUE TITLE
[SUG.] Customizable link description source

### ISSUE THREAD

**Issue by Ypot** [toshism/org-super-links#85]
Could link description use the headline of nth level?

For example,
* Book title
* * Chapter 1
* * * Unimportant section
[[Link]]

Link description could be automatically taken from second level headline? (Chapter 1 would be the description, although the link was created in the third level headline)

**Comment by toshism** [comment]
I don't think i'll add this, but like i mentioned in #83 you can create a custom function to set link descriptions to whatever you want.
