### ISSUE TITLE
Updated package on ELPA

### ISSUE THREAD

**Issue by novoid** [toshism/org-super-links#86]
Hi,

I just realized that my ELPA package verion is `20200611.155018`.

Did I miss a different installation method ([I'm using use-package](https://github.com/novoid/dot-emacs)) or is the ELPA package outdated and should get an update with a fresh release?

At least the changes here in the repo are more recent that 2020-06-11.

**Comment by toshism** [comment]
Hey, I was actually not even aware this was in ELPA. I was not responsible for that, sorry.

Personally I have switched to using [straight](https://github.com/radian-software/straight.el) for everything. I just find it much easier to manage and I don't have to deal with when ELPA/MELPA update or what packages they allow.

**Comment by novoid** [comment]
Last time I tried, I failed in setting up straight. Maybe I'll switch to a manually downloaded git repo copy. With that, I do have it all in my hands.

A bit worried though, that updating my 2020 version to an up to date version breaks a few things on my side...

Thanks anyway! Continuing to advertise your package as often as I can.

**Comment by toshism** [comment]
Yeah, whatever works for you :+1: I think you will probably have some breakage upgrading FYI. It should be minor though. I think the "namespace" changed since that version from `sl-` to `org-super-links-` so you'll need to update any of your calling code, but functionality should be pretty much the same.

**Comment by novoid** [comment]
Thank you. This will be a project for early 2024.
