### ISSUE TITLE
Depth of headings while searching for links

### ISSUE THREAD

**Issue by ecribia** [toshism/org-super-links#91]
Hi
Im not the most experienced emacs user, so please forgive my ignorance.
Im on doom emacs, and when i run org-super-links-link, the list i get has a maximum of headings level 3 that i can choose from. Heading level 4 and below are not visible. Any idea on how to fix this?

If i manually go to the 4th heading and store the link, i can then insert the link from the register. But it would be neat if i could do this directly from org-super-links-link

**Comment by iantor** [comment]
I figured out that normally, org-super-links uses org-refile to find targets.
I configured org-refile-targets to look to a maxlevel of 5:

 (setq org-refile-targets '(("organizer.org" :maxlevel . 5)))

That worked!
